run:
  timeout: 5m
  modules-download-mode: readonly

linters-settings:
  stylecheck:
    # Disable ST1003 (suggests using camelCase instead of PascalCase)
    checks: ["all", "-ST1003"]

linters:
  disable-all: true
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - stylecheck
    - gosimple
    - ineffassign
    - unused
    - misspell

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck 