// Package docs Code generated by swaggo/swag at 2025-07-31 18:33:21.068784357 +0100 BST m=+2.023868967. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://locally.cloud/terms",
        "contact": {
            "name": "API Support",
            "url": "https://locally.cloud/support",
            "email": "support@locally.cloud"
        },
        "license": {
            "name": "Fair Source License",
            "url": "https://locally.cloud/license"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {},
    "securityDefinitions": {
        "ApiKeyAuth": {
            "description": "API key for authentication",
            "type": "apiKey",
            "name": "X-API-Key",
            "in": "header"
        },
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    },
    "tags": [
        {
            "description": "Authentication and authorization endpoints",
            "name": "Authentication"
        },
        {
            "description": "User management operations",
            "name": "Users"
        },
        {
            "description": "Tenant management operations",
            "name": "Tenants"
        },
        {
            "description": "Context and environment management",
            "name": "Contexts"
        },
        {
            "description": "Message processing and worker management",
            "name": "Messages"
        },
        {
            "description": "Certificate management operations",
            "name": "Certificates"
        },
        {
            "description": "Environment variable management",
            "name": "Environment"
        },
        {
            "description": "Event management and notifications",
            "name": "Events"
        },
        {
            "description": "Worker and task management",
            "name": "Workers"
        },
        {
            "description": "Health check and status endpoints",
            "name": "Health"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "Locally API",
	Description:      "A comprehensive API for managing local development environments, contexts, and services.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
