package icons

const (
	IconHammer           string = "\xF0\x9F\x94\xA8 "
	IconFire             string = "\xF0\x9F\x94\xA5 "
	IconWrench           string = "\xF0\x9F\x94\xA7 "
	IconKey              string = "\xF0\x9F\x94\x91 "
	IconLock             string = "\xF0\x9F\x94\x92 "
	IconOpenLock         string = "\xF0\x9F\x94\x93 "
	IconBell             string = "\xF0\x9F\x94\x94 "
	IconMagnifyingGlass  string = "\xF0\x9F\x94\x8D "
	IconBook             string = "\xF0\x9F\x93\x94 "
	IconBulb             string = "\xF0\x9F\x92\xA1 "
	IconBomb             string = "\xF0\x9F\x92\xA3 "
	IconLargeWhiteSquare string = "\xE2\xAC\x9C "
	IconCircle           string = "\xE2\x9A\xAB "
	IconWarning          string = "\xE2\x9A\xA0 "
	IconRightArrow       string = "\xE2\x96\xB6 "
	IconHourGlass        string = "\xE2\x8C\x9B "
	IconInfo             string = "\xE2\x84\xB9 "
	IconFlag             string = "\xF0\x9F\x9A\xA9 "
	IconRocket           string = "\xF0\x9F\x9A\x80 "
	IconCheckMark        string = "\xE2\x9C\x85 "
	IconCrossMark        string = "\xE2\x9D\x8C "
	IconRevolvingLight   string = "\xF0\x9F\x9A\xA8 "
	IconBlackSquare      string = "\xE2\x97\xBE "
	IconFolder           string = "\xF0\x9F\x93\x81 "
	IconClipboard        string = "\xF0\x9F\x93\x8B "
	IconRightwardsArrow  string = "\xE2\x96\xB6 "
	IconExclamationMark  string = "\xE2\x9D\x95 "
	IconAsterisk         string = "\xE2\x9C\xB3 "
	IconRightHand        string = "\xF0\x9F\x91\x89 "
	IconCheckbox         string = "\xE2\x98\x91 "
	IconToilet           string = "\xF0\x9F\x9A\xBD "
	IconThumbsUp         string = "\xF0\x9F\x91\x8D "
	IconThumbDown        string = "\xF0\x9F\x91\x8E "
	IconPage             string = "\xF0\x9F\x93\x84 "
)
