package azure_cli

// Generated by https://quicktype.io

type AzureCLIVersion struct {
	AzureCLI          string            `json:"azure-cli"`
	AzureCLICore      string            `json:"azure-cli-core"`
	AzureCLITelemetry string            `json:"azure-cli-telemetry"`
	Extensions        map[string]string `json:"extensions"`
}
