package azure_cli

// Generated by https://quicktype.io

type ServicePrincipalResponse struct {
	AppID       string `json:"appId"`
	DisplayName string `json:"displayName"`
	Password    string `json:"password"`
	TenantId    string `json:"tenant"`
}
