---
#############################
#############################
## JavaScript Linter rules ##
#############################
#############################

############
# Env Vars #
############
env:
  browser: true
  es6: true
  jest: true

###############
# Global Vars #
###############
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly

ignorePatterns:
  - "!.*"
  - "**/node_modules/.*"

###############
# Parser vars #
###############
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
  sourceType: module

###########
# Plugins #
###########
plugins:
  - '@typescript-eslint'

#########
# Rules #
#########
rules: { 
  "jsonc/no-comments": 'off',
}

##############################
# Overrides for JSON parsing #
##############################
overrides:

  # JSONC files
  - files:
      - "*.jsonc"
    extends:
      - plugin:jsonc/recommended-with-jsonc
    parser: jsonc-eslint-parser
    parserOptions:
      jsonSyntax: JSONC
      comments: false

  # JSON5 files
  - files:
      - "*.json5"
    extends:
      - plugin:jsonc/recommended-with-json5
    parser: jsonc-eslint-parser
    parserOptions:
      jsonSyntax: JSON5