name: CI Release

on:
  pull_request:
    types: 
      - closed
    branches: 
      - master
jobs:
  build:
    name: Build and Test
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      debug: false
      run_tests: false
      bump_version: false
      name: locally
  publish_release:
    name: Publish Release
    uses: ./.github/workflows/publish_release.yml
    secrets: inherit
    needs: build
    with:
      name: locally
      debug: false
      enabled: true